# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import server_pb2 as server__pb2


class CdnServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamVideo = channel.unary_stream(
                '/server.CdnServer/StreamVideo',
                request_serializer=server__pb2.VideoRequest.SerializeToString,
                response_deserializer=server__pb2.Chunk.FromString,
                )
        self.UploadVideo = channel.stream_unary(
                '/server.CdnServer/UploadVideo',
                request_serializer=server__pb2.UploadRequest.SerializeToString,
                response_deserializer=server__pb2.UploadResponse.FromString,
                )


class CdnServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadVideo(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CdnServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamVideo': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamVideo,
                    request_deserializer=server__pb2.VideoRequest.FromString,
                    response_serializer=server__pb2.Chunk.SerializeToString,
            ),
            'UploadVideo': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadVideo,
                    request_deserializer=server__pb2.UploadRequest.FromString,
                    response_serializer=server__pb2.UploadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server.CdnServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CdnServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/server.CdnServer/StreamVideo',
            server__pb2.VideoRequest.SerializeToString,
            server__pb2.Chunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/server.CdnServer/UploadVideo',
            server__pb2.UploadRequest.SerializeToString,
            server__pb2.UploadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
