# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x06server\"\x1f\n\x0cVideoRequest\x12\x0f\n\x07videoId\x18\x01 \x01(\t\"\x16\n\x05\x43hunk\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"-\n\rUploadRequest\x12\x1c\n\x05\x63hunk\x18\x01 \x01(\x0b\x32\r.server.Chunk\"\x1d\n\x0eUploadResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t2\x81\x01\n\tCdnServer\x12\x34\n\x0bStreamVideo\x12\x14.server.VideoRequest\x1a\r.server.Chunk0\x01\x12>\n\x0bUploadVideo\x12\x15.server.UploadRequest\x1a\x16.server.UploadResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VIDEOREQUEST']._serialized_start=24
  _globals['_VIDEOREQUEST']._serialized_end=55
  _globals['_CHUNK']._serialized_start=57
  _globals['_CHUNK']._serialized_end=79
  _globals['_UPLOADREQUEST']._serialized_start=81
  _globals['_UPLOADREQUEST']._serialized_end=126
  _globals['_UPLOADRESPONSE']._serialized_start=128
  _globals['_UPLOADRESPONSE']._serialized_end=157
  _globals['_CDNSERVER']._serialized_start=160
  _globals['_CDNSERVER']._serialized_end=289
# @@protoc_insertion_point(module_scope)
