# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/authentication.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/authentication.proto\x12\x0e\x61uthentication\"4\n\x0e\x41\x63\x63ountRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"F\n\x0f\x41\x63\x63ountResponse\x12\x12\n\ncan_log_in\x18\x01 \x01(\x08\x12\x0e\n\x06userId\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t2\xad\x01\n\x0e\x41uthentication\x12Q\n\x0e\x63reate_account\x12\x1e.authentication.AccountRequest\x1a\x1f.authentication.AccountResponse\x12H\n\x05login\x12\x1e.authentication.AccountRequest\x1a\x1f.authentication.AccountResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.authentication_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ACCOUNTREQUEST']._serialized_start=46
  _globals['_ACCOUNTREQUEST']._serialized_end=98
  _globals['_ACCOUNTRESPONSE']._serialized_start=100
  _globals['_ACCOUNTRESPONSE']._serialized_end=170
  _globals['_AUTHENTICATION']._serialized_start=173
  _globals['_AUTHENTICATION']._serialized_end=346
# @@protoc_insertion_point(module_scope)
