# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import authentication_pb2 as proto_dot_authentication__pb2


class AuthenticationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_account = channel.unary_unary(
                '/authentication.Authentication/create_account',
                request_serializer=proto_dot_authentication__pb2.AccountRequest.SerializeToString,
                response_deserializer=proto_dot_authentication__pb2.AccountResponse.FromString,
                )
        self.login = channel.unary_unary(
                '/authentication.Authentication/login',
                request_serializer=proto_dot_authentication__pb2.AccountRequest.SerializeToString,
                response_deserializer=proto_dot_authentication__pb2.AccountResponse.FromString,
                )
        self.is_authenticated = channel.unary_unary(
                '/authentication.Authentication/is_authenticated',
                request_serializer=proto_dot_authentication__pb2.AuthenticationRequest.SerializeToString,
                response_deserializer=proto_dot_authentication__pb2.AuthenticationResponse.FromString,
                )


class AuthenticationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_account(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_authenticated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthenticationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_account': grpc.unary_unary_rpc_method_handler(
                    servicer.create_account,
                    request_deserializer=proto_dot_authentication__pb2.AccountRequest.FromString,
                    response_serializer=proto_dot_authentication__pb2.AccountResponse.SerializeToString,
            ),
            'login': grpc.unary_unary_rpc_method_handler(
                    servicer.login,
                    request_deserializer=proto_dot_authentication__pb2.AccountRequest.FromString,
                    response_serializer=proto_dot_authentication__pb2.AccountResponse.SerializeToString,
            ),
            'is_authenticated': grpc.unary_unary_rpc_method_handler(
                    servicer.is_authenticated,
                    request_deserializer=proto_dot_authentication__pb2.AuthenticationRequest.FromString,
                    response_serializer=proto_dot_authentication__pb2.AuthenticationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'authentication.Authentication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Authentication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_account(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authentication.Authentication/create_account',
            proto_dot_authentication__pb2.AccountRequest.SerializeToString,
            proto_dot_authentication__pb2.AccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authentication.Authentication/login',
            proto_dot_authentication__pb2.AccountRequest.SerializeToString,
            proto_dot_authentication__pb2.AccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def is_authenticated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authentication.Authentication/is_authenticated',
            proto_dot_authentication__pb2.AuthenticationRequest.SerializeToString,
            proto_dot_authentication__pb2.AuthenticationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
