# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import commentserver_pb2 as proto_dot_commentserver__pb2


class CommentServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_comments = channel.unary_stream(
                '/comment.CommentServer/get_comments',
                request_serializer=proto_dot_commentserver__pb2.Video.SerializeToString,
                response_deserializer=proto_dot_commentserver__pb2.CommentResponse.FromString,
                )
        self.send_message = channel.unary_unary(
                '/comment.CommentServer/send_message',
                request_serializer=proto_dot_commentserver__pb2.SendComment.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class CommentServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_comments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def send_message(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommentServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_comments': grpc.unary_stream_rpc_method_handler(
                    servicer.get_comments,
                    request_deserializer=proto_dot_commentserver__pb2.Video.FromString,
                    response_serializer=proto_dot_commentserver__pb2.CommentResponse.SerializeToString,
            ),
            'send_message': grpc.unary_unary_rpc_method_handler(
                    servicer.send_message,
                    request_deserializer=proto_dot_commentserver__pb2.SendComment.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'comment.CommentServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommentServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_comments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/comment.CommentServer/get_comments',
            proto_dot_commentserver__pb2.Video.SerializeToString,
            proto_dot_commentserver__pb2.CommentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def send_message(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/comment.CommentServer/send_message',
            proto_dot_commentserver__pb2.SendComment.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
