# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/commentserver.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/commentserver.proto\x12\x07\x63omment\x1a\x1bgoogle/protobuf/empty.proto\"B\n\x0bSendComment\x12\x10\n\x08video_id\x18\x01 \x01(\x05\x12!\n\x07\x63omment\x18\x02 \x01(\x0b\x32\x10.comment.Comment\"\x19\n\x05Video\x12\x10\n\x08video_id\x18\x01 \x01(\x05\"(\n\x07\x43omment\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\">\n\x0f\x43ommentResponse\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\t2\x89\x01\n\rCommentServer\x12:\n\x0cget_comments\x12\x0e.comment.Video\x1a\x18.comment.CommentResponse0\x01\x12<\n\x0csend_message\x12\x14.comment.SendComment\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.commentserver_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SENDCOMMENT']._serialized_start=67
  _globals['_SENDCOMMENT']._serialized_end=133
  _globals['_VIDEO']._serialized_start=135
  _globals['_VIDEO']._serialized_end=160
  _globals['_COMMENT']._serialized_start=162
  _globals['_COMMENT']._serialized_end=202
  _globals['_COMMENTRESPONSE']._serialized_start=204
  _globals['_COMMENTRESPONSE']._serialized_end=266
  _globals['_COMMENTSERVER']._serialized_start=269
  _globals['_COMMENTSERVER']._serialized_end=406
# @@protoc_insertion_point(module_scope)
