# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import server_pb2 as proto_dot_server__pb2


class CdnServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamVideo = channel.unary_stream(
                '/server.CdnServer/StreamVideo',
                request_serializer=proto_dot_server__pb2.VideoRequest.SerializeToString,
                response_deserializer=proto_dot_server__pb2.Chunk.FromString,
                )
        self.UploadVideo = channel.stream_unary(
                '/server.CdnServer/UploadVideo',
                request_serializer=proto_dot_server__pb2.UploadRequest.SerializeToString,
                response_deserializer=proto_dot_server__pb2.UploadResponse.FromString,
                )
        self.RequestToUpload = channel.unary_unary(
                '/server.CdnServer/RequestToUpload',
                request_serializer=proto_dot_server__pb2.UploadToServerRequest.SerializeToString,
                response_deserializer=proto_dot_server__pb2.UploadResponse.FromString,
                )
        self.Watch = channel.unary_unary(
                '/server.CdnServer/Watch',
                request_serializer=proto_dot_server__pb2.WatchRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.WatchWith = channel.unary_unary(
                '/server.CdnServer/WatchWith',
                request_serializer=proto_dot_server__pb2.WatchPartyRequest.SerializeToString,
                response_deserializer=proto_dot_server__pb2.PartyResponse.FromString,
                )
        self.PauseParty = channel.unary_unary(
                '/server.CdnServer/PauseParty',
                request_serializer=proto_dot_server__pb2.WatchParty.SerializeToString,
                response_deserializer=proto_dot_server__pb2.PartyResponse.FromString,
                )


class CdnServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadVideo(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestToUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchWith(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseParty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CdnServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamVideo': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamVideo,
                    request_deserializer=proto_dot_server__pb2.VideoRequest.FromString,
                    response_serializer=proto_dot_server__pb2.Chunk.SerializeToString,
            ),
            'UploadVideo': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadVideo,
                    request_deserializer=proto_dot_server__pb2.UploadRequest.FromString,
                    response_serializer=proto_dot_server__pb2.UploadResponse.SerializeToString,
            ),
            'RequestToUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestToUpload,
                    request_deserializer=proto_dot_server__pb2.UploadToServerRequest.FromString,
                    response_serializer=proto_dot_server__pb2.UploadResponse.SerializeToString,
            ),
            'Watch': grpc.unary_unary_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=proto_dot_server__pb2.WatchRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'WatchWith': grpc.unary_unary_rpc_method_handler(
                    servicer.WatchWith,
                    request_deserializer=proto_dot_server__pb2.WatchPartyRequest.FromString,
                    response_serializer=proto_dot_server__pb2.PartyResponse.SerializeToString,
            ),
            'PauseParty': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseParty,
                    request_deserializer=proto_dot_server__pb2.WatchParty.FromString,
                    response_serializer=proto_dot_server__pb2.PartyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server.CdnServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CdnServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/server.CdnServer/StreamVideo',
            proto_dot_server__pb2.VideoRequest.SerializeToString,
            proto_dot_server__pb2.Chunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/server.CdnServer/UploadVideo',
            proto_dot_server__pb2.UploadRequest.SerializeToString,
            proto_dot_server__pb2.UploadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestToUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.CdnServer/RequestToUpload',
            proto_dot_server__pb2.UploadToServerRequest.SerializeToString,
            proto_dot_server__pb2.UploadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.CdnServer/Watch',
            proto_dot_server__pb2.WatchRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WatchWith(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.CdnServer/WatchWith',
            proto_dot_server__pb2.WatchPartyRequest.SerializeToString,
            proto_dot_server__pb2.PartyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PauseParty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.CdnServer/PauseParty',
            proto_dot_server__pb2.WatchParty.SerializeToString,
            proto_dot_server__pb2.PartyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
