# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/server.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/server.proto\x12\x06server\x1a\x1bgoogle/protobuf/empty.proto\"\x1f\n\x0cVideoRequest\x12\x0f\n\x07videoId\x18\x01 \x01(\x05\"\x16\n\x05\x43hunk\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"=\n\x0eStreamResponse\x12\x1c\n\x05\x63hunk\x18\x01 \x01(\x0b\x32\r.server.Chunk\x12\r\n\x05title\x18\x02 \x01(\t\"-\n\rUploadRequest\x12\x1c\n\x05\x63hunk\x18\x01 \x01(\x0b\x32\r.server.Chunk\"\x1d\n\x0eUploadResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t\"8\n\x15UploadToServerRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"?\n\x0cWatchRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x0f\n\x07videoId\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\x03\"\x13\n\x11WatchPartyRequest\"\x0c\n\nWatchParty\"\x0f\n\rPartyResponse\"&\n\tVideoInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t2\xef\x03\n\tCdnServer\x12;\n\x0cgetAllVideos\x12\x16.google.protobuf.Empty\x1a\x11.server.VideoInfo0\x01\x12>\n\x13getVideoInformation\x12\x14.server.VideoRequest\x1a\x11.server.VideoInfo\x12\x34\n\x0bStreamVideo\x12\x14.server.VideoRequest\x1a\r.server.Chunk0\x01\x12\x36\n\x0bUploadVideo\x12\r.server.Chunk\x1a\x16.server.UploadResponse(\x01\x12H\n\x0fRequestToUpload\x12\x1d.server.UploadToServerRequest\x1a\x16.server.UploadResponse\x12\x35\n\x05Watch\x12\x14.server.WatchRequest\x1a\x16.google.protobuf.Empty\x12=\n\tWatchWith\x12\x19.server.WatchPartyRequest\x1a\x15.server.PartyResponse\x12\x37\n\nPauseParty\x12\x12.server.WatchParty\x1a\x15.server.PartyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VIDEOREQUEST']._serialized_start=59
  _globals['_VIDEOREQUEST']._serialized_end=90
  _globals['_CHUNK']._serialized_start=92
  _globals['_CHUNK']._serialized_end=114
  _globals['_STREAMRESPONSE']._serialized_start=116
  _globals['_STREAMRESPONSE']._serialized_end=177
  _globals['_UPLOADREQUEST']._serialized_start=179
  _globals['_UPLOADREQUEST']._serialized_end=224
  _globals['_UPLOADRESPONSE']._serialized_start=226
  _globals['_UPLOADRESPONSE']._serialized_end=255
  _globals['_UPLOADTOSERVERREQUEST']._serialized_start=257
  _globals['_UPLOADTOSERVERREQUEST']._serialized_end=313
  _globals['_WATCHREQUEST']._serialized_start=315
  _globals['_WATCHREQUEST']._serialized_end=378
  _globals['_WATCHPARTYREQUEST']._serialized_start=380
  _globals['_WATCHPARTYREQUEST']._serialized_end=399
  _globals['_WATCHPARTY']._serialized_start=401
  _globals['_WATCHPARTY']._serialized_end=413
  _globals['_PARTYRESPONSE']._serialized_start=415
  _globals['_PARTYRESPONSE']._serialized_end=430
  _globals['_VIDEOINFO']._serialized_start=432
  _globals['_VIDEOINFO']._serialized_end=470
  _globals['_CDNSERVER']._serialized_start=473
  _globals['_CDNSERVER']._serialized_end=968
# @@protoc_insertion_point(module_scope)
